const emailsString = `agustn.monsalve@uc.cl
agustinalb@uc.cl
amhernandez@uc.cl
bastian.valderrama@uc.cl
cata.psilva18@uc.cl
cb.arancibia@uc.cl
creyev@uc.cl
catalina.arenas@uc.cl
clara.stanke@estudiante.uc.cl
dscottb@estudiante.uc.cl
diego.vasquez@uc.cl
escarleth.carriel@uc.cl
gabriel.peillard@estudiante.uc.cl
imanol.ope@uc.cl
inaki.rojas.campora@uc.cl
ilaraya1@uc.cl
javier.subercaseaux@uc.cl
jvergarv@uc.cl
jtsoffia@uc.cl
jsuarezr@uc.cl
karen.prez@uc.cl
likan.vanhulst@estudiante.uc.cl
macarena.schneider@estudiante.uc.cl
msurez@uc.cl
florencia.herrerav@uc.cl
mtorresw@uc.cl
mrojasmuller@uc.cl
mnevares@uc.cl
maximiliano.zapata@uc.cl
miguel.martnez@uc.cl
opreece@estudiante.uc.cl
sebaleiva@uc.cl
sophia.heuze@uc.cl
teresa.leiva@uc.cl
valeria.ortiz@uc.cl
vicente.lacroix@uc.cl
vuribu@uc.cl
vguzmw@estudiante.uc.cl
agustin_salgado@uc.cl
alejandra.aravena@uc.cl
alex.torreblanca@estudiante.uc.cl
ameln@uc.cl
anastasia.vigneaux@uc.cl
anvillarreal@uc.cl
arojab@uc.cl
bnavarreteromo@uc.cl
bruno.schilling@uc.cl
diego.carrasco@uc.cl
ebordagorry@uc.cl
eduardo.garrido@uc.cl
emilia.johnson@uc.cl
espinosab@uc.cl
felipe.romn@uc.cl
fernanda.bahamonde@uc.cl
gabriela.flores@uc.cl
gastaudt@uc.cl
jbarres@uc.cl
jmcolomer@uc.cl
jmedep@uc.cl
lelepazcontreras@uc.cl
luiggi.arriagada@uc.cl
margarita.bambach@uc.cl
martina.auger@uc.cl
maxicanutdebon@uc.cl
mbernales1@uc.cl
mikaela.bachs@uc.cl
nbaez24@estudiante.uc.cl
pedro.leon@uc.cl
pedro.valero@uc.cl
rafael.silva@uc.cl
rafaela.moya@uc.cl
rrencoretj@uc.cl
tjecheverria@uc.cl
trrivera@uc.cl
agustina.caviedes@uc.cl
almendragarcia@uc.cl
antoniacampos@uc.cl
benjaminescobar@uc.cl
benjamn.roque@uc.cl
d.alliendec@estudiante.uc.cl
diego.irarrzaval@estudiante.uc.cl
diego.saavedra@uc.cl
dnsuarez@uc.cl
emilia.ilabaca@uc.cl
emiliano.vergara@estudiante.uc.cl
francisca.caldern@uc.cl
ipachecop@uc.cl
isabella.simonetti@uc.cl
javiervargas@estudiante.uc.cl
jfernnder@uc.cl
jfleaux@uc.cl
jmfaundes7@uc.cl
josema.ariztia@uc.cl
josevherrera@uc.cl
lorenzo.carvajal@uc.cl
lucas.valdivia@uc.cl
marcos.larrain@uc.cl
mtcarrillo@uc.cl
nazareth.morales@uc.cl
rrozap@uc.cl
santiago.alcalde@uc.cl
sebastianvv@uc.cl
smirandg@estudiante.uc.cl
solivo@uc.cl
susanaphillips@uc.cl
vicente.antonucci@uc.cl
vicentesanchez@uc.cl
agustinnawrathibanez@uc.cl
amacueto@uc.cl
angel.barra@uc.cl
bugartem@uc.cl
bp.silva@uc.cl
clarafornaro@uc.cl
ceduaraya@estudiante.uc.cl
dairaakemi.bs@estudiante.uc.cl
damary.rey@uc.cl
emily.yorston@estudiante.uc.cl
florencia.pulgar@estudiante.uc.cl
franco.medalla@uc.cl
gabriel.orellana@uc.cl
jalquinta@estudiante.uc.cl
joaqun.cruzat@uc.cl
jgoldenbergc@estudiante.uc.cl
karina.herrera@uc.cl
lucas.mulet@uc.cl
mariagraciakl@uc.cl
mjvalenzuelam@uc.cl
triniundurragac@uc.cl
mauda.prez@uc.cl
ndonosol.004@uc.cl
nignaciomb@estudiante.uc.cl
pnvaldivia@uc.cl
sofia.cataln@estudiante.uc.cl
tomas.feres@estudiante.uc.cl
tomasgomezromero@uc.cl
tespinolal@uc.cl
vijoroub@uc.cl
elisaachurrap@uc.cl
victoriaalvarez@estudiante.uc.cl
juanignacioayala@estudiante.uc.cl
rodrigo.brozalez@uc.cl
martina.canto@uc.cl
paulo.chicao@uc.cl
juanita.coeymans@uc.cl
tomislav.cvitanic@uc.cl
danidiazc@estudiante.uc.cl
barbara.espinozag@uc.cl
ffigueroas99@uc.cl
sofa.garrido@uc.cl
domingo.halpern@estudiante.uc.cl
raimundoholch@estudiante.uc.cl
sara.leigh@uc.cl
maite.morales@estudiante.uc.cl
raimundo.pacheco@uc.cl
hernn.palacios@uc.cl
andrespenaroa@uc.cl
dominga.quiroz@estudiante.uc.cl
catarivas@uc.cl
marcel.robin@uc.cl
david.rojas@uc.cl
valentina.ureta@uc.cl
angeles.widow@uc.cl
martinyaneza@uc.cl
mlabegorre0@estudiante.uc.cl
belen.aguilar@estudiante.uc.cl
laura.aylwin@uc.cl
emilia.canales@uc.cl
luis.cardenas@estudiante.uc.cl
martina.cariz@estudiante.uc.cl
vicente.carrillo@uc.cl
fcollao@uc.cl
mcontrerasf@uc.cl
mcorrer@estudiante.uc.cl
ceguigurens@uc.cl
iespinov@uc.cl
ngih@uc.cl
mgonzles@estudiante.uc.cl
diego.henrquez@estudiante.uc.cl
elisa.hubner@uc.cl
renatalira@uc.cl
lucas.lopez.p@uc.cl
jalorcalorca@uc.cl
demardones@uc.cl
snegra@estudiante.uc.cl
francisca.neira@uc.cl
mgperalta@uc.cl
ipetitlaurent@uc.cl
juana.pina@estudiante.uc.cl
gpiroddi@uc.cl
jose.prado@uc.cl
rpuelmav@estudiante.uc.cl
cristobal.ramirez@uc.cl
denisse.rojas@uc.cl
mrojab@uc.cl
amelie.roth@uc.cl
avergarv@estudiante.uc.cl
josefinavillalon@uc.cl
fziga@estudiante.uc.cl
anahiro@uc.cl
andres.luna@uc.cl
antonia.fernandez@estudiante.uc.cl
antonio.ferran@uc.cl
bernardita.zerene@uc.cl
ctapiaperez@uc.cl
fernandam@uc.cl
floaviles@estudiante.uc.cl
frojam@uc.cl
gmrojas2@uc.cl
isa.lucero@estudiante.uc.cl
javiera.jensen@uc.cl
javiergazituarequena@uc.cl
jmolivosq@uc.cl
josefa.rivas@uc.cl
laura.stuven@estudiante.uc.cl
mara.contreras@uc.cl
martina.gasull@uc.cl
martn.arellano@uc.cl
mateo.parra@uc.cl
matiascaro@estudiante.uc.cl
miolguin@uc.cl
mjfontbote@uc.cl
tania.moraga@estudiante.uc.cl
tomas.gouhaneh@estudiante.uc.cl
trinidad.otaegui@uc.cl
vpinot@estudiante.uc.cl
smassicot@estudiante.uc.cl
antonia.bown@uc.cl
aapablaza@uc.cl
agustina.araneda@estudiante.uc.cl
alvaro.ng@uc.cl
bmachmar@uc.cl
carlos.longeri@uc.cl
cata.cornejo@estudiante.uc.cl
elisa.rojas@estudiante.uc.cl
emilia.vilaplanal@uc.cl
fabian.az@uc.cl
felipe.rebolledo@uc.cl
felipe.sanhueza@estudiante.uc.cl
ffmorales@uc.cl
florencia.infante@uc.cl
francisco.arroyo@uc.cl
francisco.awad@estudiante.uc.cl
ialvarezd@uc.cl
isabella.molinare@uc.cl
isidora.donoso@estudiante.uc.cl
jcastrosf@estudiante.uc.cl
juan.arrau@uc.cl
jwernerf@uc.cl
kallendes@uc.cl
lpasteneg@estudiante.uc.cl
martn.cruzat@estudiante.uc.cl
meetcheberry@uc.cl
mmaino.d@estudiante.uc.cl
mpoblem@uc.cl
mspitzer@estudiante.uc.cl
nicole.ocares@estudiante.uc.cl
nparham@uc.cl
pedrorencoretgiaconi@uc.cl
santiago.albornoz@estudiante.uc.cl
seba.armijo@estudiante.uc.cl
slg@uc.cl
trojam@uc.cl
valentina.andrade@uc.cl
vicentezd@estudiante.uc.cl
vrferrada@uc.cl
angel.bachler@uc.cl
rvbitran@uc.cl
luca.blanco@estudiante.uc.cl
abruchfeld@uc.cl
iccerez@uc.cl
catalina.murua@uc.cl
mcasanuevn@uc.cl
agustin.castaer@uc.cl
acisternas@estudiante.uc.cl
natalie.condori@estudiante.uc.cl
francisco.cruzat@estudiante.uc.cl
bruno.demunter@uc.cl
srdiaze@uc.cl
iflorem@uc.cl
eduardagaliaco@estudiante.uc.cl
vguzmw@estudiante.uc.cl
trinidad.hederra@estudiante.uc.cl
vhernnda@uc.cl
santiago.kamke@estudiante.uc.cl
mlevine@uc.cl
antolopezack@estudiante.uc.cl
mclopez5@uc.cl
mlmaturana@uc.cl
damaris.medina@uc.cl
paz.merino@uc.cl
emiliano.mora@uc.cl
cmg@estudiante.uc.cl
rolivares7@uc.cl
antonia.painn@uc.cl
matias.palma@uc.cl
amanda.pardo@estudiante.uc.cl
josejoaquin.perez@estudiante.uc.cl
flo.rodriguezg@uc.cl
arojasa2@estudiante.uc.cl
lrosselp@estudiante.uc.cl
isabella.sanmiguel@uc.cl
clementetoro1@estudiante.uc.cl
teresita.turpaud@estudiante.uc.cl
ibarnao@uc.cl
dyvelasquez@uc.cl
melanie.weber@uc.cl
maximiliano.weldt@uc.cl
franciscazurita@uc.cl
maca.alvarezd@uc.cl
jbaranguiz@uc.cl
carenam@uc.cl
florencia.arriagada@uc.cl
floavilesg@uc.cl
mbidegain@uc.cl
dominga.calisto@uc.cl
jcarvac@uc.cl
gabriel.celis@uc.cl
rtcharpentier@uc.cl
agcohurtado@uc.cl
monserrat.diaz@uc.cl
sa.fzuniga@uc.cl
joaqun.garrido@uc.cl
njlopez2@uc.cl
felipelorca@uc.cl
camilamarcusruiz@uc.cl
mmirane@uc.cl
claudia.morales@uc.cl
comoreno1@uc.cl
ferv.munoz@uc.cl
francisco.nunez@uc.cl
meocampo@uc.cl
luc.olhabe@uc.cl
mariaortega@uc.cl
sebastin.ortiz@uc.cl
alfredo.pizarro@uc.cl
bpuentes@uc.cl
catalina.rozas@uc.cl
cristobalveas@uc.cl
alvarovergarav@uc.cl
gael.armstrong@uc.cl
davendam@uc.cl
cabecerrab@uc.cl
almendra.camposano@uc.cl
martina.canario@uc.cl
anai.carvajal@uc.cl
leonardo.cortes@uc.cl
n.cruzat@uc.cl
tdaccarett@uc.cl
nifernandez@uc.cl
benja.guardas@uc.cl
guzmanrocio@uc.cl
bdigor@uc.cl
kamal.lahsen@uc.cl
matmateluna@uc.cl
camilaalexaml@estudiante.uc.cl
vicente.moller@uc.cl
hgquimi@uc.cl
sirodriguezpavez@uc.cl
noelia.rubilar@uc.cl
pruizb@uc.cl
nruiza@uc.cl
bcsanchez@uc.cl
pelayo.sanchez@uc.cl
ramn.snchez@uc.cl
manuela.sanfuentes@estudiante.uc.cl
clemente.sanhueza@uc.cl
isilvab@uc.cl
evalenzuelp@uc.cl
tjvonkunowsky@uc.cl
matias.zegers@uc.cl
alejandra.lazo@uc.cl
amadisloyer@uc.cl
anais.alonso@uc.cl
caro.guzman@uc.cl
carzola@uc.cl
catalina.raby@uc.cl
catalina.reyes@uc.cl
cris.roman@uc.cl
ctramirez1@uc.cl
dllorens@uc.cl
elenafd@uc.cl
emilia.garay@uc.cl
emilia.ibez@uc.cl
emilio.castro@uc.cl
fernanda.venegas@uc.cl
ifcardemil@uc.cl
jtapio@uc.cl
luca.diaz@uc.cl
lucas.melo@uc.cl
maria.barros@uc.cl
meleck.reinike@uc.cl
michelle.ruiz@uc.cl
mlarra@uc.cl
mquezo@uc.cl
nnavia@uc.cl
pascal.prado@uc.cl
renata.farias@uc.cl
 rodrigo.cadenas@uc.cl
sebastianfloresc@uc.cl
sfouillioux@uc.cl
sophia.goldsack@uc.cl
stephanie.cubillos@uc.cl
teresanchezd@uc.cl
toms.molina@uc.cl
victoria.irarrzaval@uc.cl
vslagunas@uc.cl
vsolimano@uc.cl
martina.bergamini@estudiante.uc.cl
trinidad.lema@uc.cl`
const emails = emailsString.split('\n')
const emailsPerUcUsername: Record<string, string> = {}
emails.forEach(email => {
  const [ucUsername, extension] = email.split('@')
  emailsPerUcUsername[ucUsername] = email
})

export async function getEmail(ucUsername: string) {
  return emailsPerUcUsername[ucUsername]
}
